# Generated by Django 2.1.7 on 2019-03-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('stockid', models.IntegerField(db_column='stockID', primary_key=True, serialize=False)),
                ('stockname', models.TextField(db_column='stockName')),
                ('ownerlname', models.TextField(db_column='ownerLName')),
                ('earnings', models.TextField()),
                ('yearlyearnings', models.TextField(db_column='yearlyEarnings')),
            ],
            options={
                'db_table': 'owner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stockspractice',
            fields=[
                ('stockid', models.IntegerField(db_column='stockID', primary_key=True, serialize=False)),
                ('stockname', models.TextField(db_column='stockName')),
                ('shareno', models.TextField(db_column='shareNo')),
                ('earnings', models.TextField()),
                ('yearlyearnings', models.TextField(db_column='yearlyEarnings')),
            ],
            options={
                'db_table': 'stocksPractice',
                'managed': False,
            },
        ),
    ]
